// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using FluentUIExperiments.Models1.Configurations;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
#nullable disable

namespace FluentUIExperiments.Models1;

public partial class DataCenterWorkflowContext : DbContext
{
    public DataCenterWorkflowContext()
    {
    }

    public DataCenterWorkflowContext(DbContextOptions<DataCenterWorkflowContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Department> Department { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=DESKTOP-91FGOH1;Initial Catalog=AdventureWorks2022;Integrated Security=True");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.ApplyConfigurationsFromAssembly(typeof(DataCenterWorkflowContext).Assembly);

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
