// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using FluentUIExperiments.Models1;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace FluentUIExperiments.Models1
{
    public partial interface IDataCenterWorkflowContextProcedures
    {
        Task<List<USP_GET_INITIALIZATION_DATAResult>> USP_GET_INITIALIZATION_DATAAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<USP_GET_INITIALIZATION_DATA_1Result>> USP_GET_INITIALIZATION_DATA_1Async(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
