// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace FluentUIExperiments.Models1
{
    public partial class USP_GET_INITIALIZATION_DATA_1Result
    {
        public int CountyId { get; set; }
        public string CountyName { get; set; }
    }
}
