// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace FluentUIExperiments.Models1
{
    public partial class USP_GET_INITIALIZATION_DATAResult
    {
        public int CountyId { get; set; }
        public string CountyName { get; set; }
        public int TypeOfCountById { get; set; }
        public string TypeOfCountBysName { get; set; }
        public int TypeOfInstrumentId { get; set; }
        public string TypeOfInstrumentName { get; set; }
        public int TypeOfWorkId { get; set; }
        public string TypeOfWorksName { get; set; }
    }
}
